name: Jasmine_SHRP

on: workflow_dispatch

env:
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       
      - name: Checkout
        uses: actions/checkout@master
       
      - name: Initializing environment
        run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            git config --global user.name "Gofaraway71"
            git config --global user.email "aalbatron@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get -qq update
        
      - name: Mkaing Dir Repo and setting up Environment
        run: |
            bash
            cd 
            mkdir bin
            cd bin
            curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo 
            chmod a+x ~/bin/repo
            cd
            cd bin
            git clone https://github.com/akhilnarang/scripts.git scripts
            cd
            bash bin/scripts/setup/android_build_env.sh
            bash bin/scripts/setup/install_android_sdk.sh
   
      - name: Sync recovery source and device tree
        run: |
            cd
            mkdir SHRP
            cd SHRP
            repo init -u git://github.com/SHRP/platform_manifest_twrp_omni.git -b shrp-12.1 --depth=1
            repo sync -j8 --force-sync --optimized-fetch --no-clone-bundle
            cd
            cd SHRP
            git clone https://github.com/Rahuh-960/android_device_xiaomi_jasmine_sprout-twrp.git device/xiaomi/jasmine_sprout
            
      - name: Now Lets build Ofox
        run: |
            cd
            cd SHRP
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            lunch omni_RMX2151-eng
            mka recoveryimage
      
      - name: Uploading using Bash Upload
        run: |
            cd
            mv SHRP/out/target/product/RMX2151/OrangeFox-Unofficial-wayne.img ~
            mv SHRP/out/target/product/RMX2151/OrangeFox-Unofficial-wayne.zip ~
            curl https://bashupload.com/Ofox-Unofficial.zip --data-binary @OrangeFox-Unofficial-RMX2151.zip
            curl https://bashupload.com/Ofox-Unofficial.img --data-binary @OrangeFox-Unofficial-RMX2151.img
            
            
